cart1/urls.py
from django.urls import path
from . import views

app_name='cart'
urlpatterns = [
   
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>',views.cart_add,name='cart_add'),
    path('add_q/<int:product_id>',views.cart_add_q,name='cart_add_q'),
    path('remove/<int:product_id>',views.cart_remove,name='cart_remove'),

    
]

ease_at_home/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('account.urls')),
    path('product/',include('product.urls')),
    path('payment',include('payment.urls')),
    path('orders',include('orders.urls')),
    path('cart1',include('cart1.urls')),
    path('wishlist/',include('wishlist.urls')),

    re_path(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
app_name='orders'

urlpatterns = [
   
    path('create/',views.order_create,name="order_create"),
    path('process/',views.order_save,name="order_save"),
    path('orderview/',views.orderview,name='orderview'),
    path('orderitemview/',views.orderitemview,name='orderitemview'),
    path('neworder/',views.neworder,name="neworder"),
    path('update_order/<int:id>/',views.update_order,name="update_order"),
    path('delete_order/<int:id>/',views.delete_order,name="delete_order"),
    path('view_orders',views.view_orders,name='view_orders'),


    
]

templates/cart/cart_detail.html
<!doctype html>
<html lang="zxx">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Cleanfreshly a Home Maintenance & Service Category Bootstrap Responsive Web Template | Home :: W3layouts
	</title>
	<!-- Template CSS -->
	<link rel="stylesheet" href="/static/assets/css/style-starter.css">
	<!-- Template CSS -->
	<link href="//fonts.googleapis.com/css?family=Josefin+Sans:400,400i,500,600,700&display=swap"
		rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Lato:300,400,400i,700&display=swap" rel="stylesheet">
	<!-- Template CSS -->
</head>

<body>
	<!--w3l-header-->
	<section class="w3l-top-header-content">
		<div class="hny-top-menu">
			<div class="container">
				
			</div>
		</div>
	</section>
	<!--//top-header-content-->
	<header class="w3l-header-nav">
		<!--/nav-->
		<nav class="navbar navbar-expand-lg navbar-light fill px-lg-0 py-0 px-3">
			<div class="container">
				<h1><a class="navbar-brand" href="{% url 'index' %}">EASE @<span> HOME</span></a></h1>
				<!-- if logo is image enable this   
						<a class="navbar-brand" href="#index.html">
							<img src="image-path" alt="Your logo" title="Your logo" style="height:35px;" />
						</a> -->
				<button class="navbar-toggler collapsed" type="button" data-toggle="collapse"
					data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
					aria-label="Toggle navigation">
					<!-- <span class="navbar-toggler-icon"></span> -->
					<span class="fa icon-expand fa-bars"></span>
					<span class="fa icon-close fa-times"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item active">
							<a class="nav-link" href="index.html">Home</a>
						</li>
						{% if user.is_authenticated %}
						{% if user.is_superuser %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'admin:index' %}">ADMIN</a>
						</li>
						{% endif %}
                        <li class="nav-item">
							<a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
						</li>

						<li class="nav-item">
							<a class="nav-link" href="{% url 'user_logout' %}">Logout</a>
						</li>
						{% if user.shop %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'volunteer_register' %}">ADD VOLUNTEER</a>
						</li>
						{% endif %}

						{% else %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'registrations' %}">Register</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'user_login' %}">Login</a>
						</li>
						{% endif %}
					</ul>
					<a href="#" class="ml-lg-3 mt-lg-0 mt-3 book btn btn-secondary btn-style">Get started</a>
				</div>
			</div>
		</nav>
		<!--//nav-->
	</header>


{% block content %}
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

<table id="cart" class="table table-hover table-condensed">
    <thead>
        <tr>
            <th style="width:50%">Product</th>
            <th style="width:10%">Price</th>
            <th style="width:8%">Quantity</th>
            <th style="width:22%" class="text-center">Subtotal</th>
            <th style="width:10%"></th>
        </tr>
    </thead>

    <tbody>
        {% for item in cart.items.all %} {% with product=item.product %}
        <tr>
            <td data-th="Product">
                <div class="row">
                    <div class="col-sm-2 hidden-xs">

                        <a href="{% url 'product_detail' product.id %}">
                            <img src="{% if product.image %}{{ product.image.url }}{% endif %}" class="img-responsive" width="50px" height="50px">
                        </a>

                    </div>
                    <div class="col-sm-10">
                        <h4 class="nomargin">{{ product.name }}</h4>
                        <p>{{ product.descripion }}</p>
                    </div>
                </div>
            </td>
            <td data-th="Price"> ₹ {{ product.price }}</td>
            <td data-th="Quantity">

                <form action="{% url 'cart:cart_add_q' product.id  %}">
                    <input style="color: brown;" type="number" name="q" value="{{ item.quantity }}" class="form-control text-center" onchange="this.form.submit()"> {% csrf_token %}

                </form>

            </td>
            <td data-th="Subtotal" class="text-center">{{item.get_cost}}</td>
            <td class="actions" data-th="">

                <a href="{% url 'cart:cart_remove' product.id %}" class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i></a>
            </td>
        </tr>
        {% endwith %} {% endfor %}
    </tbody>

    <tfoot>
        <tr class="visible-xs">
            <!-- <td class="text-center"><strong>cart.</strong></td> -->
        </tr>
        <tr>
            <td><a href="{% url 'product' %}" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue Shopping</a></td>
            <td colspan="2" class="hidden-xs"></td>
            <td class="hidden-xs text-center"><strong>Total Rs. {{cart.get_total_cost}}</strong></td>
            <td><a href="{% url 'orders:order_create' %}" class="btn btn-success btn-block">Checkout <i class="fa fa-angle-right"></i></a></td>
            

        </tr>

    </tfoot>
</table>

{% endblock %}
	<!-- footer-66 -->
	<footer class="w3l-footer-66">
		<div class="footer-28-main">
			<div class="container">
				<div class="row footer-hny-top">
					<div class="col-lg-6 footer-logo pl-lg-0">
						<h2><a class="navbar-brand" href="index.html">Clean<span>Freshly</span></a></h2>
						<!-- if logo is image enable this   
						<a class="navbar-brand" href="#index.html">
							<img src="image-path" alt="Your logo" title="Your logo" style="height:35px;" />
						</a> -->
					</div>
					<div class="col-lg-6 main-social-footer-28 pr-lg-0">
						<a href="#facebook"><span class="fa fa-facebook"></a>
						<a href="#twitter"><span class="fa fa-twitter"></a>
						<a href="#google"><span class="fa fa-google-plus"></a>
						<a href="#linkedin"><span class="fa fa-linkedin"></a>
						<a href="#instagram"><span class="fa fa-instagram"></a>
					</div>
				</div>
				<div class="row footer-top-28">
					<div class="col-lg-2 col-md-6 footer-list-28 pl-lg-0">
						<h6 class="footer-title-28">Extra Links</h6>
						<ul>
							<li><a href="about.html">About Company</a></li>
							<li><a href="services.html">Our Services</a></li>
							<li><a href="portfolio.html">Recent projects list</a></li>
							<li><a href="blog.html">Latest News blog</a></li>
						</ul>
					</div>
					<div class="col-lg-5 col-md-6 footer-list-28">
						<h6 class="footer-title-28">list of Services</h6>
						<ul class="d-grid footer-column-2">
							<li><a href="services.html">Plumbing</a></li>
							<li><a href="services.html">Carpenter</a></li>
							<li><a href="services.html">Electrician</a></li>
							<li><a href="services.html">Wall painting</a></li>
							<li><a href="services.html">Furniture moving</a></li>
							<li><a href="services.html">House Cleaning</a></li>
							<li><a href="services.html">Replacing wires</a></li>
							<li><a href="services.html">AC & Refrigerator</a></li>
						</ul>
					</div>
					<div class="col-lg-2 col-md-6 footer-list-28">
						<h6 class="footer-title-28">Support</h6>
						<ul>
							<li><a href="#link">Documentation</a></li>
							<li><a href="#link">Privacy policy</a></li>
							<li><a href="#link">Terms of service</a></li>
							<li><a href="#link">24/7 support</a></li>
						</ul>
					</div>
					<div class="col-lg-3 col-md-6 footer-list-28 pr-lg-0">
						<h6 class="footer-title-28">Working Hours</h6>
						<ul class="working-hours">
							<li><span>Monday</span> : 8AM - 6AM</li>
							<li><span>Tuesday</span> : 8AM - 6AM</li>
							<li><span>Wednesday</span> : 8AM - 6AM</li>
							<li><span>Thursday - Friday </span> : 8AM - 6AM</li>
							<li><span>Sunday</span> : Closed</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="midd-footer-28 align-center">
				<p class="copy-footer-28">© 2020 Cleanfreshly. All rights reserved | Designed by <a
						href="https://w3layouts.com">W3layouts</a></p>
			</div>
		</div>
		<!-- move top -->
		<button onclick="topFunction()" id="movetop" title="Go to top">
			<span class="fa fa-angle-up"></span>
		</button>
		<script>
			// When the user scrolls down 20px from the top of the document, show the button
			window.onscroll = function () {
				scrollFunction()
			};

			function scrollFunction() {
				if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
					document.getElementById("movetop").style.display = "block";
				} else {
					document.getElementById("movetop").style.display = "none";
				}
			}

			// When the user clicks on the button, scroll to the top of the document
			function topFunction() {
				document.body.scrollTop = 0;
				document.documentElement.scrollTop = 0;
			}
		</script>
		<!-- /move top -->

	</footer>
	<!--//footer-66 -->
</body>

</html>

<script src="/static/assets/js/jquery-3.3.1.min.js"></script>
<!-- disable body scroll which navbar is in active -->

<!--//-->
<script>
	$(function () {
		$('.navbar-toggler').click(function () {
			$('body').toggleClass('noscroll');
		})
	});
</script>
<!--/scroll-down-JS-->
<!-- for blog carousel slider -->
<script src="/static/assets/js/owl.carousel.js"></script>
<!-- script for banner slider-->
<script>
	$(document).ready(function () {
		$('.owl-one').owlCarousel({
			loop: true,
			margin: 0,
			nav: false,
			responsiveClass: true,
			autoplay: false,
			autoplayTimeout: 5000,
			autoplaySpeed: 1000,
			autoplayHoverPause: false,
			responsive: {
				0: {
					items: 1,
					nav: false
				},
				480: {
					items: 1,
					nav: false
				},
				667: {
					items: 1,
					nav: true
				},
				1000: {
					items: 1,
					nav: true
				}
			}
		})
	})
</script>
<!-- //testimonials owlcarousel -->
<script>
	$(document).ready(function () {
		$('.owl-two').owlCarousel({
			loop: true,
			margin: 30,
			nav: false,
			responsiveClass: true,
			autoplay: false,
			autoplayTimeout: 5000,
			autoplaySpeed: 1000,
			autoplayHoverPause: false,
			responsive: {
				0: {
					items: 1,
					nav: false
				},
				480: {
					items: 1,
					nav: false
				},
				667: {
					items: 1,
					nav: false
				},
				1000: {
					items: 1,
					nav: false
				}
			}
		})
	})
</script>
<!-- //script for Testimonials-->
<!-- //script -->

<script src="/static/assets/js/bootstrap.min.js"></script>