account/urls.py
from os import name
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('',views.index,name="index"),
    path('shop_register',views.shop_register,name="shop_register"),
    path('user_login',views.user_login,name='user_login'),
    path('dashboard',views.dashboard,name='dashboard'),
    path('user_logout',views.user_logout,name='user_logout'),
    path('home_servicer_register',views.home_servicer_register,name="home_servicer_register"),
    path('customer_register',views.customer_register,name="customer_register"),
    path('volunteer_register',views.volunteer_register,name='volunteer_register'),
    path('registrations',views.registrations,name='registrations'),
    path('volunteer',views.volunteer,name='volunteer'),
    path('update_volunteer/<int:volunteer_id>',views.update_volunteer,name='update_volunteer'),
    path('delete_volunteer/<int:id>',views.delete_volunteer,name='delete_volunteer'),
    path('home_servicers',views.home_servicers,name='home_servicers'),
    path('servicer_booking/<int:servicer_id>',views.servicer_booking,name='servicer_booking'),
    path('view_customer_bookings',views.view_customer_bookings,name='view_customer_bookings'),
    path('view_servicer_bookings',views.view_servicer_bookings,name='view_servicer_bookings'),
    path('delete_booking/<int:id>',views.delete_booking,name='delete_booking'),
    path('update_booking/<int:booking_id>',views.update_booking,name='update_booking'),
    path('volunteer_availability',views.update_availablity_volunteer,name='volunteer_availability'),
    path('servicer_availability',views.update_availablity_servicer,name='servicer_availability'),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart1/urls.py
from django.urls import path
from . import views

app_name='cart'
urlpatterns = [
   
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>',views.cart_add,name='cart_add'),
    path('add_q/<int:product_id>',views.cart_add_q,name='cart_add_q'),
    path('remove/<int:product_id>',views.cart_remove,name='cart_remove'),

    
]

ease_at_home/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('account.urls')),
    path('product/',include('product.urls')),
    path('payment',include('payment.urls')),
    path('orders',include('orders.urls')),
    path('cart1',include('cart1.urls')),
    path('wishlist/',include('wishlist.urls')),

    re_path(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
app_name='orders'

urlpatterns = [
   
    path('create/',views.order_create,name="order_create"),
    path('process/',views.order_save,name="order_save"),
    path('orderview/',views.orderview,name='orderview'),
    path('orderitemview/',views.orderitemview,name='orderitemview'),
    path('neworder/',views.neworder,name="neworder"),
    path('update_order/<int:id>/',views.update_order,name="update_order"),
    path('delete_order/<int:id>/',views.delete_order,name="delete_order"),
    path('view_orders',views.view_orders,name='view_orders'),


    
]

payment/urls.py
from django.urls import path
from .import views

app_name = 'payment'
urlpatterns = [
    path('payment',views.payment,name='payment'),
    path('servicer_payment/<int:booking_id>',views.servicer_payment,name='servicer_payment'),
    path('payment-status', views.payment_status, name='payment-status'),
    path('allpayment',views.allpayments,name='allpayment'),
    path('userpayment',views.userpaymentview,name='userpayment')


    
]

wishlist/urls.py
from django.urls import path
from  .import views

app_name = 'wishlist'
urlpatterns = [

    path('add/<int:product_id>',views.wishlist_add,name='wishlist_add'),

    path('remove/<int:product_id>/',views.wishlist_remove,name='wishlist_remove'),

    path('', views.wishlist_detail, name='wishlist_detail')
]

account/forms.py
from django import forms
from django.db.models import fields
from django.forms.fields import DateField
from . models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User



class UserForm(UserCreationForm):
    username=forms.CharField(help_text=None,label='Username')
    password1=forms.CharField(help_text=None,widget=forms.PasswordInput,label='Password')
    password2=forms.CharField(help_text=None,widget=forms.PasswordInput,label='Confirm Password')
    class Meta:
        model=User
        fields=('username','password1','password2','email')
        labels=('password1','password','password2','confirm password')



class ShopRegisterForm(forms.ModelForm):
    class Meta:
        model=Shop
        fields=('shop_name','phone','license_no','location','proof','category')


class HomeServicerRegisterForm(forms.ModelForm):
    class Meta:
        model=HomeServicer
        fields=('phone','location','proof','qualification','category')



class CustomerRegisterForm(forms.ModelForm):
    class Meta:
        model=Customer
        fields=('phone','location')



class VolunteerRegisterForm(forms.ModelForm):
    class Meta:
        model=Volunteer
        fields=('phone','qualification','location','id_proof')



class UpdateForm(forms.ModelForm):
    username=forms.CharField(help_text=None,label='Username')
    
    class Meta:
        model=User
        fields=('username',)

class UpdateProfileForm(forms.ModelForm):
    address=forms.Textarea()
    
    class Meta:
        model=Volunteer
        fields=('phone','qualification','location','id_proof')


class VolunteerAvailabilityForm(forms.ModelForm):
    available='available'
    not_available='not_available'
    availability_statuses=[
        (available,'available'),
        (not_available,'not_available')
    ]
    availability_status=forms.ChoiceField(choices=availability_statuses,required=True)
    
    class Meta:
        model=Volunteer
        fields=('availability_status',)


class ServicerAvailabilityForm(forms.ModelForm):
    available='available'
    not_available='not_available'
    availability_statuses=[
        (available,'available'),
        (not_available,'not_available')
    ]
    availability_status=forms.ChoiceField(choices=availability_statuses,required=True)
    
    class Meta:
        model=HomeServicer
        fields=('availability_status',)



class BookingForm(forms.ModelForm):
    wanted_date=DateField(widget=forms.SelectDateWidget)
    class Meta:
        model=Booking
        fields=('wanted_date','place')

class UpdateBookingForm(forms.ModelForm):
    class Meta:
        model=Booking
        fields=('status','paid_status','amount')

account/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from . models import *
from . forms import *
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages

# Create your views here.


def index(request):
    return render(request,'index.html')



def shop_register(request):
    reg=False
    if request.method=='POST':
        user_form=UserForm(data=request.POST)
        shop_form=ShopRegisterForm(request.POST,request.FILES)
        if user_form.is_valid() and shop_form.is_valid():
            user=user_form.save()
            user.save()
            profile=shop_form.save(commit=False)
            profile.user=user
            profile.save()

            reg=True
            return redirect('user_login')
        else:
            HttpResponse("invalid form")
    else:
         user_form=UserForm()
         shop_form=ShopRegisterForm()
    return render(request,'shop_register.html',{'register':reg,'user_form':user_form,'shop_form':shop_form}) 




def home_servicer_register(request):
    reg=False
    if request.method=='POST':
        user_form=UserForm(data=request.POST)
        homeservicer_form=HomeServicerRegisterForm(request.POST,request.FILES)
        if user_form.is_valid() and homeservicer_form.is_valid():
            user=user_form.save()
            user.save()
            profile=homeservicer_form.save(commit=False)
            profile.user=user
            profile.save()

            reg=True
            return redirect('user_login')
        else:
            HttpResponse("invalid form")
    else:
         user_form=UserForm()
         homeservicer_form=HomeServicerRegisterForm()
    return render(request,'homeservicer_register.html',{'register':reg,'user_form':user_form,'homeservicer_form':homeservicer_form}) 



def customer_register(request):
    reg=False
    if request.method=='POST':
        user_form=UserForm(data=request.POST)
        customer_form=CustomerRegisterForm(request.POST,request.FILES)
        if user_form.is_valid() and customer_form.is_valid():
            user=user_form.save()
            user.save()
            profile=customer_form.save(commit=False)
            profile.user=user
            profile.save()

            reg=True
            return redirect('user_login')
        else:
            HttpResponse("invalid form")
    else:
         user_form=UserForm()
         customer_form=CustomerRegisterForm()
    return render(request,'customer_register.html',{'register':reg,'user_form':user_form,'customer_form':customer_form}) 



def volunteer_register(request):
    reg=False
    if request.method=='POST':
        shop=Shop.objects.get(user=request.user)
        print(shop)
        user_form=UserForm(data=request.POST)
        volunteer_form=VolunteerRegisterForm(request.POST,request.FILES)
        if user_form.is_valid() and volunteer_form.is_valid():
            user=user_form.save()
            user.save()
            profile=volunteer_form.save(commit=False)

            profile.user=user
            profile.shop=shop
            profile.save()

            reg=True
            return redirect('user_login')
        else:
            HttpResponse("invalid form")
    else:
         user_form=UserForm()
         volunteer_form=VolunteerRegisterForm()
    return render(request,'volunteer_register.html',{'register':reg,'user_form':user_form,'volunteer_form':volunteer_form}) 



def registrations(request):
    return render(request,'registrations.html')




def user_login(request):
    if request.method=="POST":
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('dashboard'))
            else:
                return HttpResponse("Not active")
        else:
            return HttpResponse("Invalid username or password")
    else:
        
        return render(request,'login.html')


def dashboard(request):
    #list=Todo.objects.all()
    return render(request,'dashboard.html')



@login_required
def user_logout(request):
    logout(request)
    return redirect('index')



def volunteer(request):
    our_volunteer=Volunteer.objects.filter(shop=request.user.shop,availability_status='available')
    print(our_volunteer)
    return render(request,'our_volunteer.html',{'our_volunteer':our_volunteer})


def update_volunteer(request,volunteer_id):
    my_volunteer=Volunteer.objects.get(id=volunteer_id)
    if request.method=="POST":
        my_volunteer=Volunteer.objects.get(id=volunteer_id)
        update_form=UpdateForm(request.POST,instance=my_volunteer.user)
        
        update_profile_form=UpdateProfileForm(request.POST,instance=my_volunteer)
        
        if update_form.is_valid() and update_profile_form.is_valid():
            update_form.save()
            update_profile_form.save()
            messages.success(request,f'Your Account has been Updated')
            return redirect('dashboard')
    else:
        update_form=UpdateForm(instance=my_volunteer.user)
        update_profile_form=UpdateProfileForm(instance=my_volunteer)
    context={
        'update_form':update_form,
        'update_profile_form':update_profile_form
    }
    return render(request,'update_volunteer.html',context)



def delete_volunteer(request,id):
    deleteemp = Volunteer.objects.get(id=id)
    deleteemp.delete()
    messages.success(request,'Record deleted succefully')
    return redirect('volunteer')



def home_servicers(request):
    category=HomeServicerCategory.objects.all()
    if request.method=="GET":
        category=HomeServicerCategory.objects.all()
        location=request.GET.get('location')
        category1=request.GET.get('category')
        try:
            servicer=HomeServicer.objects.filter(location__icontains=location) and HomeServicer.objects.filter(category=category1,availability_status='available')
            print(servicer)
            return render(request,'home_servicers.html',{'servicer':servicer,'category':category})
        except:
            pass
        
    return render(request,'home_servicers.html',{'category':category})



def servicer_booking(request,servicer_id):
    servicer=HomeServicer.objects.get(id=servicer_id)
    if request.method=="POST":
        servicer=HomeServicer.objects.get(id=servicer_id)
        booking_form=BookingForm(request.POST)
        if booking_form.is_valid():
            bookings=Booking(customer=request.user.customer,wanted_date=booking_form.cleaned_data['wanted_date'],place=booking_form.cleaned_data['place'])
            bookings.servicer=servicer
            bookings.save()
            return redirect('view_customer_bookings')
        else:
            return HttpResponse("Invalid Form")
    booking_form=BookingForm()
    return render(request,'booking_form.html',{'booking_form':booking_form})


def view_customer_bookings(request):
    customer_bookings=Booking.objects.filter(customer=request.user.customer)
    
    print(customer_bookings)
    return render(request,'view_bookings.html',{'customer_bookings':customer_bookings})


def view_servicer_bookings(request):
    servicer_bookings=Booking.objects.filter(servicer=request.user.homeservicer)
    print(servicer_bookings)
    return render(request,'view_bookings.html',{'servicer_bookings':servicer_bookings})


def delete_booking(request,id):
    delete_booking = Booking.objects.get(id=id)
    delete_booking.delete()
    messages.success(request,'Record deleted succefully')
    return redirect('view_customer_bookings')


def update_booking(request,booking_id):
    booking=Booking.objects.get(id=booking_id)
    print(booking)
    update_booking_form=UpdateBookingForm(instance=booking)
    if request.method=="POST":
        update_booking_form=UpdateBookingForm(request.POST,request.FILES,instance=booking)
        update_booking_form.save()
        return redirect('view_servicer_bookings')
    return render(request,'update_bookings.html',{'update_booking_form':update_booking_form})



def update_availablity_volunteer(request):
    my_volunteer=Volunteer.objects.get(user=request.user)
    print(my_volunteer.availability_status)
    if request.method=="POST":
        my_volunteer=Volunteer.objects.get(user=request.user)
        update_form=VolunteerAvailabilityForm(request.POST,instance=my_volunteer)
        print(my_volunteer.availability_status)
        if update_form.is_valid():
            update_form.save()
            
            messages.success(request,f'Your Account has been Updated')
            return redirect('dashboard')
    else:
        update_form=VolunteerAvailabilityForm(instance=my_volunteer.user)
        
    context={
        'update_form':update_form,
        
    }
    return render(request,'update_volunteer_availability.html',context)



def update_availablity_servicer(request):
    my_servicer=HomeServicer.objects.get(user=request.user)
    print(my_servicer.availability_status)
    if request.method=="POST":
        my_servicer=HomeServicer.objects.get(user=request.user)
        update_form=ServicerAvailabilityForm(request.POST,instance=my_servicer)
        print(my_servicer.availability_status)
        if update_form.is_valid():
            update_form.save()
            
            messages.success(request,f'Your Account has been Updated')
            return redirect('dashboard')
    else:
        update_form=VolunteerAvailabilityForm(instance=my_servicer.user)
        
    context={
        'update_form':update_form,
        
    }
    return render(request,'update_servicer_availability.html',context)

account/templates/customer_register.html
{% extends 'index.html' %}{% load crispy_forms_tags %}
{% block content %} 
<div style="background-color: aquamarine;padding-top: 2em;padding-bottom: 2em;">
    <center>
{% if register %}<h1> Thank you for Registering</h1>
{% else %}
<h1 style="font-weight: bold;">Customer Register form</h1>
<form action="" method="POST" style="font-size: 20px;font-weight: bold;" enctype="multipart/form-data">
    {% csrf_token %}
    {{user_form|crispy}}{{customer_form|crispy}}
    <input type="submit" value="REGISTER" style="margin-top: 1em;background-color: brown;">
</form>
{% endif %}
</center>
</div>

{% endblock %}

account/templates/dashboard.html
{% extends 'index.html' %}


{% block content %}
<h1 >{{user.username}}</h1><br>
<div  class="row">
<div style="background:url(static/images/5.jpg);background-size: 190em 40em;background-repeat: no-repeat;padding-top: 4em;padding-bottom: 11em;padding-left: 2em;" class="row">


{% if user.shop %}
<a href="{% url 'product_create' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true" style="margin-right: 2em;height: 5em;width: 13em;padding-top: 1.5em;">ADD PRODUCTS</a>
<a href="{% url 'view_my_products' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true" style="margin-right: 2em;height: 5em;width: 13em;padding-top: 1.5em;">VIEW PRODUCTS</a>
<a href="{% url 'orders:view_orders' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true" style="margin-right: 2em;height: 5em;width: 13em;padding-top: 1.5em;">VIEW ORDERS</a>
<a href="{% url 'volunteer' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true" style="margin-right: 2em;height: 5em;width: 13em;padding-top: 1.6em;">VIEW OUR EMPLOYEES</a>
{% endif %}



{% if user.customer %}

<a href="{% url 'view_all_products' %}" class="btn btn-primary btn-lg active col-10 col-lg-3 ml-4 b1" role="button" aria-pressed="true" style="margin-right: 2em;height: 5em;padding-top: 1.5em;">VIEW PRODUCTS</a>
<a href="{% url 'orders:neworder' %}" class="btn btn-primary btn-lg active col-10 col-lg-3 ml-4 b1" role="button" aria-pressed="true" style="margin-right: 2em;height: 5em;padding-top: 1.5em;">VIEW ORDERS</a>
<a href="{% url 'cart:cart_detail' %}" class="btn btn-primary btn-lg active col-10 col-lg-3 ml-4 b1" role="button" aria-pressed="true" style="margin-right: 2em;height: 5em;padding-top: 1.5em;">VIEW CART</a>
<a href="{% url 'home_servicers' %}" class="btn btn-primary btn-lg active col-10 col-lg-3 ml-4 b1" role="button" aria-pressed="true" style="margin-right: 2em;height: 5em;padding-top: 1.5em;">HOME SERVICERS</a>
<a href="{% url 'view_customer_bookings' %}" class="btn btn-primary btn-lg active col-10 col-lg-3 ml-4 b1" role="button" aria-pressed="true" style="margin-right: 2em;height: 5em;padding-top: 1.5em;">VIEW BOOKINGS</a>
<a href="{% url 'wishlist:wishlist_detail' %}" class="btn btn-primary btn-lg active col-10 col-lg-3 ml-4 b1" role="button" aria-pressed="true" style="margin-right: 2em;height: 5em;padding-top: 1.5em">VIEW WISHLIST</a>


{% endif %}

{% if user.volunteer %}

<a href="{% url 'orders:view_orders' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true" style="margin-right: 2em;height: 5em;width: 13em;padding-top: 1.5em;">VIEW ORDERS</a>
<a href="{% url 'volunteer_availability' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true" style="margin-right: 2em;height: 5em;width: 13em;padding-top: 1.5em;">UPDATE AVAILABILITY</a>

{% endif %}


{% if user.homeservicer %}
<a href="{% url 'view_servicer_bookings' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true" style="margin-right: 2em;height: 5em;width: 13em;padding-top: 1.5em;">VIEW BOOKINGS</a>
<a href="{% url 'servicer_availability' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true" style="margin-right: 2em;height: 5em;width: 13em;padding-top: 1.5em;">UPDATE AVAILABILITY</a>
{% endif %}


</div>
</div>

{% endblock %}

account/templates/home_servicers.html
{% extends 'index.html' %}

{% block content %}

<div>

    <form action="" method="GET"> 
        {% csrf_token %}
        <label for="">Location</label>
        <input type="text" name='location'>
        <label for="bank" >Select Category: </label> <select name="category" >
            {% for i in category %}
            <option value="{{i.id}}" name="category">{{i.servicer_category_name}}</option>
            {% endfor %}
        </select>
        <input type="submit" value='SEARCH'>
    
    </form>
    
    
    
    
    </div>


    <div style="background-color: navajowhite;padding-top: 2em;padding-bottom: 3em;">
        {% for i in servicer %}
        
        <div class="card" style="margin-left: 1em;margin-right: 1em;margin-bottom: 1em;">
            <h5 class="card-header">Name: {{i.user.username}}</h5>
            <div class="card-body">
              <h5 class="card-title">Phone Number: {{i.phone}}</h5>
              <p class="card-text">Location: {{i.location}}</p>
              <p class="card-text">Availability: {{i.availability_status}}</p>
              <p class="card-text">Qualification: {{i.qualification}}</p>
              <a href="{% url 'servicer_booking' i.id %}" class="btn btn-primary">BOOK</a>
              
            </div>
          </div>
        
        {% endfor %}
        </div>



{% endblock %}

account/templates/homeservicer_register.html
{% extends 'index.html' %}{% load crispy_forms_tags %}
{% block content %} 
<div style="background-color: aquamarine;padding-top: 2em;padding-bottom: 2em;">
    <center>
{% if register %}<h1> Thank you for Registering</h1>
{% else %}
<h1 style="font-weight: bold;">Home Servicer Register form</h1>
<form action="" method="POST" style="font-size: 20px;font-weight: bold;" enctype="multipart/form-data">
    {% csrf_token %}
    {{user_form|crispy}}{{homeservicer_form|crispy}}
    <input type="submit" value="REGISTER" style="margin-top: 1em;background-color: brown;">
</form>
{% endif %}
</center>
</div>

{% endblock %}

account/templates/login.html
<!DOCTYPE html>
<html lang="zxx">

<head>
	<title>Snow Login form Responsive Widget Template : W3Layouts</title>

	<!-- Meta tags -->
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">

	<!-- Style -->
	<link rel="stylesheet" href="/static/css/style1.css" type="text/css" media="all" />
</head>

<body>
	<!-- login form -->
	<section class="w3l-login">
		<div class="overlay">
			<div class="wrapper">
				<div class="logo">
					<a class="brand-logo" href="{% url 'index' %}">EASE AT HOME LOGIN</a>
				</div>
				<div class="form-section">
					<h3>Login</h3>
					<h6>To continue with Us</h6>
					<form action="" method="POST" class="signin-form">
                        {% csrf_token %}
						<div class="form-input">
							<input type="text" name="username" placeholder="Username" required="" autofocus>
						</div>
						<div class="form-input">
							<input type="password" name="password" placeholder="Password" required="">
						</div>
						
						<button type="submit" class="btn btn-primary theme-button mt-4">Log in</button>
						
					</form>
					<p class="signup">Don’t have account yet? <a href="" class="signuplink">Sign Up</a></p>
				</div>
			</div>
		</div>
		<div id='stars'></div>
		<div id='stars2'></div>
		<div id='stars3'></div>

		<!-- copyright -->
		
		<!-- //copyright -->
	</section>

	<!-- /login form -->
</body>

</html>

account/templates/view_bookings.html
{% extends 'index.html' %}

{% block content %}


<div>
    {% if user.customer %}
    <div id="page-wrapper" style="background-color: wheat;padding-top: 3em;padding-bottom: 2em;">
        <div class="main-page">
            <div class="forms">
                <h3 class="title1"></h3>
                    <h4>Booking Table</h4>
                    
                    <table class="table">
                        <thead>
                            <tr>
                            <th>#</th>
                              
                              <th>Name</th>
                              <th>Photo</th>
                              <th>Date</th>
                              
                              <th>Wanted Date</th>
                              <th>Place</th>
                              <th>Amount</th>
                              <th>Status</th>
                              <th>Payment Status</th>
                              <th>PAY</th>
                              <th>Delete</th>

                             
                            </tr>
                        </thead>
                        {% for l in customer_bookings %}
                        <tbody style="background-color: slategrey;font-size: 15px;">
                            <tr>
                                <td class="serial">{{ forloop.counter }}</td>

                              
                              <td>{{l.servicer.user.username}}</td>
                              <td><a href="{{l.servicer.proof.url}}"><img src="{{l.servicer.proof.url}}" width="40px" height="40px"></a></td>
                              <td>{{l.date}}</td>
                              <td>{{l.wanted_date}}</td>
                              <td>{{l.amount}}</td>
                              
                              <td>{{l.place}}</td>
                              <td>{{l.status}}</td>
                              {% if l.paid_status == 'paid' %}
                          <td style="color: green;font-weight: bold;font-size: 20px;">{{l.paid_status}}</td>
                          {% else %}
                          <td style="color: red;font-weight: bold;font-size: 20px;">{{l.paid_status}}</td>
                          {% endif %}
                          {% if l.paid_status == 'notpaid' %}
                              <td><a href="{% url 'payment:servicer_payment' l.id %}">PAY</a></td>
                              {% else %}
                              <td style="color: green;font-weight: bold;font-size: 20px;">{{l.paid_status}}</td>
                              {% endif %}
                              <td><a href="{% url 'delete_booking' l.id%}" style="color: red;" onclick="return confirm('are u sure d u want to delete this record')">Delete</a></td>
                              

                            </tr>
                            
                        </tbody>
                        {% endfor %}
                    </table>
                </div>
            </div>

                
        </div>
    </div>
</div>
</div>
{% endif %}



{% if user.homeservicer %}

<div id="page-wrapper" style="background-color: wheat;padding-top: 3em;padding-bottom: 2em;">
    <div class="main-page">
        <div class="forms">
            <h3 class="title1"></h3>
                <h4>Booking Table</h4>
                <div>{% if messages %} {% for mess in messages %}
                    <b style="color: brown;">{{mess}}</b> {% endfor %} {% endif %}</div>
            </div>
                <table class="table">
                    <thead>
                        <tr>
                        <th>#</th>
                          
                          <th>Name</th>
                          
                          <th>Date</th>
                          
                          <th>Wanted Date</th>
                          <th>Place</th>
                          <th>Amount</th>
                          <th>Status</th>
                          <th>Payment Status</th>
                          <th>Update</th>

                         
                        </tr>
                    </thead>
                    {% for l in servicer_bookings %}
                    <tbody style="background-color: slategrey;font-size: 15px;">
                        <tr>
                            <td class="serial">{{ forloop.counter }}</td>

                          
                          <td>{{l.customer.user.username}}</td>
                          
                          <td>{{l.date}}</td>
                          <td>{{l.wanted_date}}</td>
                          
                          <td>{{l.place}}</td>
                          <td>{{l.amount}}</td>
                          <td>{{l.status}}</td>
                          {% if l.paid_status == 'paid' %}
                          <td style="color: green;font-weight: bold;font-size: 20px;">{{l.paid_status}}</td>
                          {% else %}
                          <td style="color: red;font-weight: bold;font-size: 20px;">{{l.paid_status}}</td>
                          {% endif %}
                          <td><a href="{% url 'update_booking' l.id %}" style="color: red;">Update Booking</a></td>
                          
                          

                        </tr>
                        
                    </tbody>
                    {% endfor %}
                </table>
            </div>
        </div>

            
    </div>
</div>
</div>
</div>

{% endif %}

</div>


{% endblock %}