cart1/urls.py
from django.urls import path
from . import views

app_name='cart'
urlpatterns = [
   
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>',views.cart_add,name='cart_add'),
    path('add_q/<int:product_id>',views.cart_add_q,name='cart_add_q'),
    path('remove/<int:product_id>',views.cart_remove,name='cart_remove'),

    
]

ease_at_home/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('account.urls')),
    path('product/',include('product.urls')),
    path('payment',include('payment.urls')),
    path('orders',include('orders.urls')),
    path('cart1',include('cart1.urls')),
    path('wishlist/',include('wishlist.urls')),

    re_path(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wishlist/urls.py
from django.urls import path
from  .import views

app_name = 'wishlist'
urlpatterns = [

    path('add/<int:product_id>',views.wishlist_add,name='wishlist_add'),

    path('remove/<int:product_id>/',views.wishlist_remove,name='wishlist_remove'),

    path('', views.wishlist_detail, name='wishlist_detail')
]

wishlist/models.py
from django.db import models
from account.models import User
from product.models import Product


# Create your models here.
class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'wishlist of {}'.format(self.user.username)


class WishlistItem(models.Model):

    wishlist = models.ForeignKey(
        Wishlist,
        related_name='wishlist_items',
        null=True,
        on_delete=models.CASCADE,
    )
    product = models.ForeignKey(Product, related_name='wishlist_item',
    on_delete=models.CASCADE,
    
    )

    def __str__(self):
        return '{}'.format(self.product.name)

wishlist/views.py
from django.shortcuts import render

from django.shortcuts import render, redirect, 	get_object_or_404
from product.models import Product
from django.contrib.auth.decorators import login_required
from .models import Wishlist, WishlistItem
from account.models import *
# Create your views here.


@login_required
def wishlist_add(request, product_id,):

    obj, created = Wishlist.objects.update_or_create(user=request.user)
    product = get_object_or_404(Product, id=product_id)
    item, itemCreated = WishlistItem.objects.update_or_create(wishlist=obj, product=product)
    obj.wishlist_items.add(item)
    item.save()
    obj.save()
    return redirect('wishlist:wishlist_detail')




def wishlist_remove(request, product_id):
    obj, created = Wishlist.objects.update_or_create(user=request.user)
    product = get_object_or_404(Product, id=product_id)
    wishlistItems = WishlistItem.objects.filter(wishlist=obj, product=product)
    wishlistItems.delete()
    return redirect('wishlist:wishlist_detail')


@login_required
def wishlist_detail(request):
    wishlist = Wishlist.objects.get(user=request.user)
    return render(request, 'wishlist/wishlist_detail.html', {'wishlist': wishlist})

templates/wishlist/wishlist_detail.html
<!doctype html>
<html lang="zxx">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Cleanfreshly a Home Maintenance & Service Category Bootstrap Responsive Web Template | Home :: W3layouts
	</title>
	<!-- Template CSS -->
	<link rel="stylesheet" href="/static/assets/css/style-starter.css">
	<!-- Template CSS -->
	<link href="//fonts.googleapis.com/css?family=Josefin+Sans:400,400i,500,600,700&display=swap"
		rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Lato:300,400,400i,700&display=swap" rel="stylesheet">
	<!-- Template CSS -->
</head>

<body>
	<!--w3l-header-->
	<section class="w3l-top-header-content">
		<div class="hny-top-menu">
			<div class="container">
				
			</div>
		</div>
	</section>
	<!--//top-header-content-->
	<header class="w3l-header-nav">
		<!--/nav-->
		<nav class="navbar navbar-expand-lg navbar-light fill px-lg-0 py-0 px-3">
			<div class="container">
				<h1><a class="navbar-brand" href="{% url 'index' %}">EASE @<span> HOME</span></a></h1>
				<!-- if logo is image enable this   
						<a class="navbar-brand" href="#index.html">
							<img src="image-path" alt="Your logo" title="Your logo" style="height:35px;" />
						</a> -->
				<button class="navbar-toggler collapsed" type="button" data-toggle="collapse"
					data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
					aria-label="Toggle navigation">
					<!-- <span class="navbar-toggler-icon"></span> -->
					<span class="fa icon-expand fa-bars"></span>
					<span class="fa icon-close fa-times"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item active">
							<a class="nav-link" href="index.html">Home</a>
						</li>
						{% if user.is_authenticated %}
						{% if user.is_superuser %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'admin:index' %}">ADMIN</a>
						</li>
						{% endif %}
                        <li class="nav-item">
							<a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
						</li>

						<li class="nav-item">
							<a class="nav-link" href="{% url 'user_logout' %}">Logout</a>
						</li>
						{% if user.shop %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'volunteer_register' %}">ADD VOLUNTEER</a>
						</li>
						{% endif %}

						{% else %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'registrations' %}">Register</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'user_login' %}">Login</a>
						</li>
						{% endif %}
					</ul>
					<a href="#" class="ml-lg-3 mt-lg-0 mt-3 book btn btn-secondary btn-style">Get started</a>
				</div>
			</div>
		</nav>
		<!--//nav-->
	</header>
{% load crispy_forms_tags %} {% load static %}


{%block content %}
{% if user.is_authenticated %}

<style>
    
</style>
<link rel="stylesheet" type="text/css" href="/static/css/style.css">
<link rel="stylesheet" type="text/css" href="/static/css/bootstap.css">

<link rel="stylesheet" type="text/css" href="/static/assets/css/card.css">
<link href="//fonts.googleapis.com/css?family=Oswald:300,400,500,600&display=swap" rel="stylesheet">
  <link href="//fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,900&display=swap" rel="stylesheet">
  <div class="main">
    <div class="wrap">
       

<div class="layout">
    <section class="inner">
        <h2><a href="{% url 'view_all_products' %}" class="btn btn-warning">Next Product to purchase</h2></a>
        <br><br>
        <ul class="grid">
            <div class="column" style="column-width: 12em; ">

            {% for item in wishlist.wishlist_items.all %} {% with product=item.product %}
            <div class="row" style="float: left; row-gap: 10px;">

            <li class="grid-tile" style="column-width: auto;" >
                <div class="item" >
                    <a href="">
                        <img width="200px" height="100px" src="{% if product.image.url %}{{ product.image.url }}{% endif %}">
                    </a>

                    <br><br>
                    <div class="item-pnl">
                        <div class="pnl-wrapper">
                            <div class="pnl-description">

                                <span class="pnl-label">{{product.name}}</span>
                                <span class="pnl-price">Rs. {{product.price}}</span>
                            </div>

                            <div class="pnl-tocart">
                                <div class="pnl-ic-wrapper">
                                    <a href="{% url  'cart:cart_add' product.id %}">
                                        <span class="pnl-ic"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" height="24" width="24" x="0px" y="0px" viewBox="0 0 32 32" style="enable-background:new 0 0 32 32;" xml:space="preserve"><g><path d="M25.4,29H6.6c-1.7,0-3-1.4-2.8-2.9l1.9-13.8C5.9,11,6.6,10,8,10h16c1.4,0,2.1,1,2.3,2.3l1.9,13.8 C28.4,27.6,27.1,29,25.4,29z"></path><path d="M10.6,12.7V8.4C10.6,5.4,13,3,16,3h0c3,0,5.4,2.4,5.4,5.4v4.3"></path></g></svg></span>
                                        cart

                                    </a>
                                    <a href="{% url  'wishlist:wishlist_remove' product.id %}">
                                        <span class="pnl-ic"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M3 6v18h18v-18h-18zm5 14c0 .552-.448 1-1 1s-1-.448-1-1v-10c0-.552.448-1 1-1s1 .448 1 1v10zm5 0c0 .552-.448 1-1 1s-1-.448-1-1v-10c0-.552.448-1 1-1s1 .448 1 1v10zm5 0c0 .552-.448 1-1 1s-1-.448-1-1v-10c0-.552.448-1 1-1s1 .448 1 1v10zm4-18v2h-20v-2h5.711c.9 0 1.631-1.099 1.631-2h5.315c0 .901.73 2 1.631 2h5.712z"/></svg></span>
                                        delete
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    </div>
                   
            </li>
        </div>
        {% endwith %} {% endfor %}
        
        </ul>
    </div>
    </section>
</div>
{% else %}
<h1>Please Login to get more..</h1>
{% endif %}
</div>
</div>
{% endblock %}
	<!-- footer-66 -->
	<footer class="w3l-footer-66">
		<div class="footer-28-main">
			<div class="container">
				<div class="row footer-hny-top">
					<div class="col-lg-6 footer-logo pl-lg-0">
						<h2><a class="navbar-brand" href="index.html">Clean<span>Freshly</span></a></h2>
						<!-- if logo is image enable this   
						<a class="navbar-brand" href="#index.html">
							<img src="image-path" alt="Your logo" title="Your logo" style="height:35px;" />
						</a> -->
					</div>
					<div class="col-lg-6 main-social-footer-28 pr-lg-0">
						<a href="#facebook"><span class="fa fa-facebook"></a>
						<a href="#twitter"><span class="fa fa-twitter"></a>
						<a href="#google"><span class="fa fa-google-plus"></a>
						<a href="#linkedin"><span class="fa fa-linkedin"></a>
						<a href="#instagram"><span class="fa fa-instagram"></a>
					</div>
				</div>
				<div class="row footer-top-28">
					<div class="col-lg-2 col-md-6 footer-list-28 pl-lg-0">
						<h6 class="footer-title-28">Extra Links</h6>
						<ul>
							<li><a href="about.html">About Company</a></li>
							<li><a href="services.html">Our Services</a></li>
							<li><a href="portfolio.html">Recent projects list</a></li>
							<li><a href="blog.html">Latest News blog</a></li>
						</ul>
					</div>
					<div class="col-lg-5 col-md-6 footer-list-28">
						<h6 class="footer-title-28">list of Services</h6>
						<ul class="d-grid footer-column-2">
							<li><a href="services.html">Plumbing</a></li>
							<li><a href="services.html">Carpenter</a></li>
							<li><a href="services.html">Electrician</a></li>
							<li><a href="services.html">Wall painting</a></li>
							<li><a href="services.html">Furniture moving</a></li>
							<li><a href="services.html">House Cleaning</a></li>
							<li><a href="services.html">Replacing wires</a></li>
							<li><a href="services.html">AC & Refrigerator</a></li>
						</ul>
					</div>
					<div class="col-lg-2 col-md-6 footer-list-28">
						<h6 class="footer-title-28">Support</h6>
						<ul>
							<li><a href="#link">Documentation</a></li>
							<li><a href="#link">Privacy policy</a></li>
							<li><a href="#link">Terms of service</a></li>
							<li><a href="#link">24/7 support</a></li>
						</ul>
					</div>
					<div class="col-lg-3 col-md-6 footer-list-28 pr-lg-0">
						<h6 class="footer-title-28">Working Hours</h6>
						<ul class="working-hours">
							<li><span>Monday</span> : 8AM - 6AM</li>
							<li><span>Tuesday</span> : 8AM - 6AM</li>
							<li><span>Wednesday</span> : 8AM - 6AM</li>
							<li><span>Thursday - Friday </span> : 8AM - 6AM</li>
							<li><span>Sunday</span> : Closed</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="midd-footer-28 align-center">
				<p class="copy-footer-28">© 2020 Cleanfreshly. All rights reserved | Designed by <a
						href="https://w3layouts.com">W3layouts</a></p>
			</div>
		</div>
		<!-- move top -->
		<button onclick="topFunction()" id="movetop" title="Go to top">
			<span class="fa fa-angle-up"></span>
		</button>
		<script>
			// When the user scrolls down 20px from the top of the document, show the button
			window.onscroll = function () {
				scrollFunction()
			};

			function scrollFunction() {
				if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
					document.getElementById("movetop").style.display = "block";
				} else {
					document.getElementById("movetop").style.display = "none";
				}
			}

			// When the user clicks on the button, scroll to the top of the document
			function topFunction() {
				document.body.scrollTop = 0;
				document.documentElement.scrollTop = 0;
			}
		</script>
		<!-- /move top -->

	</footer>
	<!--//footer-66 -->
</body>

</html>

<script src="/static/assets/js/jquery-3.3.1.min.js"></script>
<!-- disable body scroll which navbar is in active -->

<!--//-->
<script>
	$(function () {
		$('.navbar-toggler').click(function () {
			$('body').toggleClass('noscroll');
		})
	});
</script>
<!--/scroll-down-JS-->
<!-- for blog carousel slider -->
<script src="/static/assets/js/owl.carousel.js"></script>
<!-- script for banner slider-->
<script>
	$(document).ready(function () {
		$('.owl-one').owlCarousel({
			loop: true,
			margin: 0,
			nav: false,
			responsiveClass: true,
			autoplay: false,
			autoplayTimeout: 5000,
			autoplaySpeed: 1000,
			autoplayHoverPause: false,
			responsive: {
				0: {
					items: 1,
					nav: false
				},
				480: {
					items: 1,
					nav: false
				},
				667: {
					items: 1,
					nav: true
				},
				1000: {
					items: 1,
					nav: true
				}
			}
		})
	})
</script>
<!-- //testimonials owlcarousel -->
<script>
	$(document).ready(function () {
		$('.owl-two').owlCarousel({
			loop: true,
			margin: 30,
			nav: false,
			responsiveClass: true,
			autoplay: false,
			autoplayTimeout: 5000,
			autoplaySpeed: 1000,
			autoplayHoverPause: false,
			responsive: {
				0: {
					items: 1,
					nav: false
				},
				480: {
					items: 1,
					nav: false
				},
				667: {
					items: 1,
					nav: false
				},
				1000: {
					items: 1,
					nav: false
				}
			}
		})
	})
</script>
<!-- //script for Testimonials-->
<!-- //script -->

<script src="/static/assets/js/bootstrap.min.js"></script>