cart1/urls.py
from django.urls import path
from . import views

app_name='cart'
urlpatterns = [
   
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>',views.cart_add,name='cart_add'),
    path('add_q/<int:product_id>',views.cart_add_q,name='cart_add_q'),
    path('remove/<int:product_id>',views.cart_remove,name='cart_remove'),

    
]

ease_at_home/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('account.urls')),
    path('product/',include('product.urls')),
    path('payment',include('payment.urls')),
    path('orders',include('orders.urls')),
    path('cart1',include('cart1.urls')),
    path('wishlist/',include('wishlist.urls')),

    re_path(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from .import views

app_name = 'payment'
urlpatterns = [
    path('payment',views.payment,name='payment'),
    path('servicer_payment/<int:booking_id>',views.servicer_payment,name='servicer_payment'),
    path('payment-status', views.payment_status, name='payment-status'),
    path('allpayment',views.allpayments,name='allpayment'),
    path('userpayment',views.userpaymentview,name='userpayment')


    
]

payment/models.py
from django.db import models
from cart1.models import *
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Payment(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)
    # name=models.CharField(max_length=20)
    amount = models.CharField(max_length=100)
    payment_id=models.CharField(max_length=200,blank=True)
    order_id=models.CharField(max_length=20,blank=True)
    is_paid=models.BooleanField(default=False)
    # cart=models.ForeignKey(Cart,on_delete=models.CASCADE,blank=True,null=True)
    total_amount=models.PositiveIntegerField(default=0)
    all_total=models.PositiveIntegerField(default=0)
    date=models.DateTimeField(default=timezone.now)

    
    def __str__(self):
        return str(self.user)

    def save(self,*args,**kwargs):
        if self.is_paid == True:
            self.all_total=self.all_total+int(self.total_amount)
            print(self.all_total)
        super().save(*args, **kwargs)

payment/forms.py
from django import forms
from django.db.models import fields
from .models import *
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout,Submit

class PaymentForm(forms.ModelForm):
    class Meta:
        model=Payment
        fields = ('amount',)
    # def __init__(self,*args,**kwargs):
    #     super().__init__(*args,**kwargs)
    #     self.helper=FormHelper(self)
    #     self.helper.layout=Layout(
    #         'name',
    #         'amount',
    #         Submit('submit','Pay_Now',css_class='button white btn-block btn-primary')
    #     )

payment/views.py
from django.contrib import messages
from django.db.models.fields import PositiveIntegerField

from account.models import Booking
from .models import *
from django.shortcuts import render
import razorpay
from .forms import PaymentForm
from cart1.models import *
from orders.models import *

def payment(request):
    t=request.user.cart.total_amount
    cart=Cart.objects.get(user=request.user)
    order=request.session['order']
    orders=Order.objects.get(id=order)
    print(orders.paid)

    if request.method == "POST":
        # name = request.POST.get('name')
        # amount1=request.POST.get('amount')
        amount = t *100
        client = razorpay.Client(auth=('rzp_test_48Z9LMTDVAN5JU', 'gMxfhwgZ73ANYJQCeblLMy7W'))
        response_payment = client.order.create(dict(amount=amount,
                                                    currency='INR')
                                               )

        order_id = response_payment['id']
        order_status = response_payment['status']
        print(request.user.cart.total_amount)
        t=request.user.cart.total_amount
        
        if order_status == 'created':
            payment = Payment(
                amount=t,
                order_id=order_id,
                total_amount=t,
                user=request.user,
                
            )
          
        payment.save()
        order=request.session['order']
        orders=Order.objects.get(id=order)
        print(orders.paid)
        requirement=Order.objects.update_or_create(id=order,
        defaults={'paid':True}
        )
        print(orders.paid)
        
        response_payment['user'] = request.user
        cart=Cart.objects.get(user=request.user)
        form = PaymentForm(request.POST or None)
        return render(request, 'payment/payment.html', {'form':form,'payment': response_payment,'cart':cart})

    form = PaymentForm()
    return render(request, 'payment/payment.html', {'form': form,'amount':t,'cart':cart})






def servicer_payment(request,booking_id):
    
    booking=Booking.objects.get(id=booking_id)
    print(booking)
    print(booking.amount)

    if request.method == "POST":
        # name = request.POST.get('name')
        # amount1=request.POST.get('amount')
        amount = booking.amount *100
        client = razorpay.Client(auth=('rzp_test_48Z9LMTDVAN5JU', 'gMxfhwgZ73ANYJQCeblLMy7W'))
        response_payment = client.order.create(dict(amount=amount,
                                                    currency='INR')
                                               )

        order_id = response_payment['id']
        order_status = response_payment['status']
        print(request.user.cart.total_amount)
        t=request.user.cart.total_amount
        
        if order_status == 'created':
            payment = Payment(
                amount=booking.amount,
                order_id=order_id,
                total_amount=booking.amount,
                user=request.user,
                
            )
          
        payment.save()
        order=Booking.objects.update_or_create(id=booking_id,
        defaults={'paid_status':'paid'}
        )
        response_payment['user'] = request.user

        form = PaymentForm(request.POST or None)
        return render(request, 'payment/servicer_payment.html', {'form':form,'payment': response_payment,'amount':booking.amount})

    form = PaymentForm()
    return render(request, 'payment/servicer_payment.html', {'form': form,'amount':booking.amount})



def payment_status(request):
    response = request.POST
    params_dict = {

       'razorpay_order_id': response['razorpay_order_id'],
       'razorpay_payment_id': response['razorpay_payment_id'],
       'razorpay_signature': response['razorpay_signature'],
     
    }

    # client instance
    client = razorpay.Client(auth=('rzp_test_48Z9LMTDVAN5JU', 'gMxfhwgZ73ANYJQCeblLMy7W'))
    

    try:
        status = client.utility.verify_payment_signature(params_dict)
        payment = Payment.objects.get(order_id=response['razorpay_order_id'])
        payment.payment_id = response['razorpay_payment_id']

        payment.is_paid = True
        payment.save()
        return render(request, 'payment/payment_status.html', {'status': True,'payment_id':payment.payment_id})
    except:
        return render(request, 'payment/payment_status.html', {'status': False})


def allpayments(request):
    payall=Payment.objects.all()
    return render(request,'payment/allpayment.html',{'payall':payall})

def userpaymentview(request):
    userpay=Payment.objects.filter(user=request.user)
    return render(request,'payment/userpayment.html',{'userpay':userpay})

templates/payment/payment.html
<!doctype html>
<html lang="zxx">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Cleanfreshly a Home Maintenance & Service Category Bootstrap Responsive Web Template | Home :: W3layouts
	</title>
	<!-- Template CSS -->
	<link rel="stylesheet" href="/static/assets/css/style-starter.css">
	<!-- Template CSS -->
	<link href="//fonts.googleapis.com/css?family=Josefin+Sans:400,400i,500,600,700&display=swap"
		rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Lato:300,400,400i,700&display=swap" rel="stylesheet">
	<!-- Template CSS -->
</head>

<body>
	<!--w3l-header-->
	<section class="w3l-top-header-content">
		<div class="hny-top-menu">
			<div class="container">
				
			</div>
		</div>
	</section>
	<!--//top-header-content-->
	<header class="w3l-header-nav">
		<!--/nav-->
		<nav class="navbar navbar-expand-lg navbar-light fill px-lg-0 py-0 px-3">
			<div class="container">
				<h1><a class="navbar-brand" href="{% url 'index' %}">EASE @<span> HOME</span></a></h1>
				<!-- if logo is image enable this   
						<a class="navbar-brand" href="#index.html">
							<img src="image-path" alt="Your logo" title="Your logo" style="height:35px;" />
						</a> -->
				<button class="navbar-toggler collapsed" type="button" data-toggle="collapse"
					data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
					aria-label="Toggle navigation">
					<!-- <span class="navbar-toggler-icon"></span> -->
					<span class="fa icon-expand fa-bars"></span>
					<span class="fa icon-close fa-times"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item active">
							<a class="nav-link" href="index.html">Home</a>
						</li>
						{% if user.is_authenticated %}
						{% if user.is_superuser %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'admin:index' %}">ADMIN</a>
						</li>
						{% endif %}
                        <li class="nav-item">
							<a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
						</li>

						<li class="nav-item">
							<a class="nav-link" href="{% url 'user_logout' %}">Logout</a>
						</li>
						{% if user.shop %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'volunteer_register' %}">ADD VOLUNTEER</a>
						</li>
						{% endif %}

						{% else %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'registrations' %}">Register</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'user_login' %}">Login</a>
						</li>
						{% endif %}
					</ul>
					<a href="#" class="ml-lg-3 mt-lg-0 mt-3 book btn btn-secondary btn-style">Get started</a>
				</div>
			</div>
		</nav>
		<!--//nav-->
	</header>


{% load crispy_forms_tags %}{% block content %}
<div style="margin-bottom: 1em;">
<center><h1>Payment

</h1></center>
{% for msg in messages %}{{msg}}{% endfor %}
<form action="" method="POST">
    {% csrf_token %}
    <div class="container" style="width: 40%; background-color: #40e3ac;border-radius: 5px; padding: 30px;">
         User name: {{user.username}}<br>
         Amount:{{cart.get_total_cost}}<br><br>
        <input type="submit" value="PAY">
        {% if r == 2 %}
        <h1>not</h1>
        {% endif %}
    </form>

<br /> {% if payment %}
<form action="{% url 'payment:payment-status' %}" method="POST">
    {% csrf_token %}
    <script src="https://checkout.razorpay.com/v1/checkout.js" data-key="rzp_test_48Z9LMTDVAN5JU" data-amount="{{ cart.get_total_cost }}" data-currency="{{ payment.currency }}" data-order_id="{{payment.id}}" data-buttontext="Pay with Razorpay" data-name="Buy Your Products"
        data-description="and place your products" data-image="https://example.com/your_logo.jpg" data-prefill.name="{{ payment.name }}" data-prefill.email="you@example.com" data-theme.color="#F37254"></script>
    <input type="hidden" custom="Hidden Element" name="hidden">
</form>{% endif %}

</div>
</div>
{% endblock %}

	<!-- footer-66 -->
	<footer class="w3l-footer-66">
		<div class="footer-28-main">
			<div class="container">
				<div class="row footer-hny-top">
					<div class="col-lg-6 footer-logo pl-lg-0">
						<h2><a class="navbar-brand" href="index.html">Clean<span>Freshly</span></a></h2>
						<!-- if logo is image enable this   
						<a class="navbar-brand" href="#index.html">
							<img src="image-path" alt="Your logo" title="Your logo" style="height:35px;" />
						</a> -->
					</div>
					<div class="col-lg-6 main-social-footer-28 pr-lg-0">
						<a href="#facebook"><span class="fa fa-facebook"></a>
						<a href="#twitter"><span class="fa fa-twitter"></a>
						<a href="#google"><span class="fa fa-google-plus"></a>
						<a href="#linkedin"><span class="fa fa-linkedin"></a>
						<a href="#instagram"><span class="fa fa-instagram"></a>
					</div>
				</div>
				<div class="row footer-top-28">
					<div class="col-lg-2 col-md-6 footer-list-28 pl-lg-0">
						<h6 class="footer-title-28">Extra Links</h6>
						<ul>
							<li><a href="about.html">About Company</a></li>
							<li><a href="services.html">Our Services</a></li>
							<li><a href="portfolio.html">Recent projects list</a></li>
							<li><a href="blog.html">Latest News blog</a></li>
						</ul>
					</div>
					<div class="col-lg-5 col-md-6 footer-list-28">
						<h6 class="footer-title-28">list of Services</h6>
						<ul class="d-grid footer-column-2">
							<li><a href="services.html">Plumbing</a></li>
							<li><a href="services.html">Carpenter</a></li>
							<li><a href="services.html">Electrician</a></li>
							<li><a href="services.html">Wall painting</a></li>
							<li><a href="services.html">Furniture moving</a></li>
							<li><a href="services.html">House Cleaning</a></li>
							<li><a href="services.html">Replacing wires</a></li>
							<li><a href="services.html">AC & Refrigerator</a></li>
						</ul>
					</div>
					<div class="col-lg-2 col-md-6 footer-list-28">
						<h6 class="footer-title-28">Support</h6>
						<ul>
							<li><a href="#link">Documentation</a></li>
							<li><a href="#link">Privacy policy</a></li>
							<li><a href="#link">Terms of service</a></li>
							<li><a href="#link">24/7 support</a></li>
						</ul>
					</div>
					<div class="col-lg-3 col-md-6 footer-list-28 pr-lg-0">
						<h6 class="footer-title-28">Working Hours</h6>
						<ul class="working-hours">
							<li><span>Monday</span> : 8AM - 6AM</li>
							<li><span>Tuesday</span> : 8AM - 6AM</li>
							<li><span>Wednesday</span> : 8AM - 6AM</li>
							<li><span>Thursday - Friday </span> : 8AM - 6AM</li>
							<li><span>Sunday</span> : Closed</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="midd-footer-28 align-center">
				<p class="copy-footer-28">© 2020 Cleanfreshly. All rights reserved | Designed by <a
						href="https://w3layouts.com">W3layouts</a></p>
			</div>
		</div>
		<!-- move top -->
		<button onclick="topFunction()" id="movetop" title="Go to top">
			<span class="fa fa-angle-up"></span>
		</button>
		<script>
			// When the user scrolls down 20px from the top of the document, show the button
			window.onscroll = function () {
				scrollFunction()
			};

			function scrollFunction() {
				if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
					document.getElementById("movetop").style.display = "block";
				} else {
					document.getElementById("movetop").style.display = "none";
				}
			}

			// When the user clicks on the button, scroll to the top of the document
			function topFunction() {
				document.body.scrollTop = 0;
				document.documentElement.scrollTop = 0;
			}
		</script>
		<!-- /move top -->

	</footer>
	<!--//footer-66 -->
</body>

</html>

<script src="/static/assets/js/jquery-3.3.1.min.js"></script>
<!-- disable body scroll which navbar is in active -->

<!--//-->
<script>
	$(function () {
		$('.navbar-toggler').click(function () {
			$('body').toggleClass('noscroll');
		})
	});
</script>
<!--/scroll-down-JS-->
<!-- for blog carousel slider -->
<script src="/static/assets/js/owl.carousel.js"></script>
<!-- script for banner slider-->
<script>
	$(document).ready(function () {
		$('.owl-one').owlCarousel({
			loop: true,
			margin: 0,
			nav: false,
			responsiveClass: true,
			autoplay: false,
			autoplayTimeout: 5000,
			autoplaySpeed: 1000,
			autoplayHoverPause: false,
			responsive: {
				0: {
					items: 1,
					nav: false
				},
				480: {
					items: 1,
					nav: false
				},
				667: {
					items: 1,
					nav: true
				},
				1000: {
					items: 1,
					nav: true
				}
			}
		})
	})
</script>
<!-- //testimonials owlcarousel -->
<script>
	$(document).ready(function () {
		$('.owl-two').owlCarousel({
			loop: true,
			margin: 30,
			nav: false,
			responsiveClass: true,
			autoplay: false,
			autoplayTimeout: 5000,
			autoplaySpeed: 1000,
			autoplayHoverPause: false,
			responsive: {
				0: {
					items: 1,
					nav: false
				},
				480: {
					items: 1,
					nav: false
				},
				667: {
					items: 1,
					nav: false
				},
				1000: {
					items: 1,
					nav: false
				}
			}
		})
	})
</script>
<!-- //script for Testimonials-->
<!-- //script -->

<script src="/static/assets/js/bootstrap.min.js"></script>

templates/payment/process.html
<!doctype html>
<html lang="zxx">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Cleanfreshly a Home Maintenance & Service Category Bootstrap Responsive Web Template | Home :: W3layouts
	</title>
	<!-- Template CSS -->
	<link rel="stylesheet" href="/static/assets/css/style-starter.css">
	<!-- Template CSS -->
	<link href="//fonts.googleapis.com/css?family=Josefin+Sans:400,400i,500,600,700&display=swap"
		rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Lato:300,400,400i,700&display=swap" rel="stylesheet">
	<!-- Template CSS -->
</head>

<body>
	<!--w3l-header-->
	<section class="w3l-top-header-content">
		<div class="hny-top-menu">
			<div class="container">
				
			</div>
		</div>
	</section>
	<!--//top-header-content-->
	<header class="w3l-header-nav">
		<!--/nav-->
		<nav class="navbar navbar-expand-lg navbar-light fill px-lg-0 py-0 px-3">
			<div class="container">
				<h1><a class="navbar-brand" href="{% url 'index' %}">EASE @<span> HOME</span></a></h1>
				<!-- if logo is image enable this   
						<a class="navbar-brand" href="#index.html">
							<img src="image-path" alt="Your logo" title="Your logo" style="height:35px;" />
						</a> -->
				<button class="navbar-toggler collapsed" type="button" data-toggle="collapse"
					data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
					aria-label="Toggle navigation">
					<!-- <span class="navbar-toggler-icon"></span> -->
					<span class="fa icon-expand fa-bars"></span>
					<span class="fa icon-close fa-times"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item active">
							<a class="nav-link" href="index.html">Home</a>
						</li>
						{% if user.is_authenticated %}
						{% if user.is_superuser %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'admin:index' %}">ADMIN</a>
						</li>
						{% endif %}
                        <li class="nav-item">
							<a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
						</li>

						<li class="nav-item">
							<a class="nav-link" href="{% url 'user_logout' %}">Logout</a>
						</li>
						{% if user.shop %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'volunteer_register' %}">ADD VOLUNTEER</a>
						</li>
						{% endif %}

						{% else %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'registrations' %}">Register</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'user_login' %}">Login</a>
						</li>
						{% endif %}
					</ul>
					<a href="#" class="ml-lg-3 mt-lg-0 mt-3 book btn btn-secondary btn-style">Get started</a>
				</div>
			</div>
		</nav>
		<!--//nav-->
	</header>


{% load crispy_forms_tags %} {% block content %}
<meta charset="utf-8" />

<link href='http://fonts.googleapis.com/css?family=Roboto:400,300,700|Open+Sans:700' rel='stylesheet' type='text/css'>
<script type="text/javascript" src="/static/js/jquery.mobile.customized.min.js"></script>
<script type="text/javascript" src="/static/js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="/static/js/camera.min.js"></script>
<script type="text/javascript" src="/static/js/myscript.js"></script>
<script src="/static/js/sorting.js" type="text/javascript"></script>
<script src="/static/js/jquery.isotope.js" type="text/javascript"></script>
<!--script type="text/javascript" src="static/js/jquery.nav.js"></script-->
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
<!--link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
     <link rel="stylesheet" href="static/css/login_style.css"-->


<script>
    jQuery(function() {
        jQuery('#camera_wrap_1').camera({
            transPeriod: 500,
            time: 3000,
            height: '490px',
            thumbnails: false,
            pagination: true,
            playPause: false,
            loader: false,
            navigation: false,
            hover: false
        });
        status
    });
</script>
<div style="background-color: palevioletred;">
    <center style="padding-top: 10em; padding-bottom: 20em;">
<button class="paybutton" style="border-style: solid; border-color: lawngreen; background-color: lightcoral; height: 100px; width: 200px;" ><a href="{% url 'payment:payment' %}"><h1>PAY NOW</h1></a></button> 
</center>
</div>

{% endblock %}
	<!-- footer-66 -->
	<footer class="w3l-footer-66">
		<div class="footer-28-main">
			<div class="container">
				<div class="row footer-hny-top">
					<div class="col-lg-6 footer-logo pl-lg-0">
						<h2><a class="navbar-brand" href="index.html">Clean<span>Freshly</span></a></h2>
						<!-- if logo is image enable this   
						<a class="navbar-brand" href="#index.html">
							<img src="image-path" alt="Your logo" title="Your logo" style="height:35px;" />
						</a> -->
					</div>
					<div class="col-lg-6 main-social-footer-28 pr-lg-0">
						<a href="#facebook"><span class="fa fa-facebook"></a>
						<a href="#twitter"><span class="fa fa-twitter"></a>
						<a href="#google"><span class="fa fa-google-plus"></a>
						<a href="#linkedin"><span class="fa fa-linkedin"></a>
						<a href="#instagram"><span class="fa fa-instagram"></a>
					</div>
				</div>
				<div class="row footer-top-28">
					<div class="col-lg-2 col-md-6 footer-list-28 pl-lg-0">
						<h6 class="footer-title-28">Extra Links</h6>
						<ul>
							<li><a href="about.html">About Company</a></li>
							<li><a href="services.html">Our Services</a></li>
							<li><a href="portfolio.html">Recent projects list</a></li>
							<li><a href="blog.html">Latest News blog</a></li>
						</ul>
					</div>
					<div class="col-lg-5 col-md-6 footer-list-28">
						<h6 class="footer-title-28">list of Services</h6>
						<ul class="d-grid footer-column-2">
							<li><a href="services.html">Plumbing</a></li>
							<li><a href="services.html">Carpenter</a></li>
							<li><a href="services.html">Electrician</a></li>
							<li><a href="services.html">Wall painting</a></li>
							<li><a href="services.html">Furniture moving</a></li>
							<li><a href="services.html">House Cleaning</a></li>
							<li><a href="services.html">Replacing wires</a></li>
							<li><a href="services.html">AC & Refrigerator</a></li>
						</ul>
					</div>
					<div class="col-lg-2 col-md-6 footer-list-28">
						<h6 class="footer-title-28">Support</h6>
						<ul>
							<li><a href="#link">Documentation</a></li>
							<li><a href="#link">Privacy policy</a></li>
							<li><a href="#link">Terms of service</a></li>
							<li><a href="#link">24/7 support</a></li>
						</ul>
					</div>
					<div class="col-lg-3 col-md-6 footer-list-28 pr-lg-0">
						<h6 class="footer-title-28">Working Hours</h6>
						<ul class="working-hours">
							<li><span>Monday</span> : 8AM - 6AM</li>
							<li><span>Tuesday</span> : 8AM - 6AM</li>
							<li><span>Wednesday</span> : 8AM - 6AM</li>
							<li><span>Thursday - Friday </span> : 8AM - 6AM</li>
							<li><span>Sunday</span> : Closed</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="midd-footer-28 align-center">
				<p class="copy-footer-28">© 2020 Cleanfreshly. All rights reserved | Designed by <a
						href="https://w3layouts.com">W3layouts</a></p>
			</div>
		</div>
		<!-- move top -->
		<button onclick="topFunction()" id="movetop" title="Go to top">
			<span class="fa fa-angle-up"></span>
		</button>
		<script>
			// When the user scrolls down 20px from the top of the document, show the button
			window.onscroll = function () {
				scrollFunction()
			};

			function scrollFunction() {
				if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
					document.getElementById("movetop").style.display = "block";
				} else {
					document.getElementById("movetop").style.display = "none";
				}
			}

			// When the user clicks on the button, scroll to the top of the document
			function topFunction() {
				document.body.scrollTop = 0;
				document.documentElement.scrollTop = 0;
			}
		</script>
		<!-- /move top -->

	</footer>
	<!--//footer-66 -->
</body>

</html>

<script src="/static/assets/js/jquery-3.3.1.min.js"></script>
<!-- disable body scroll which navbar is in active -->

<!--//-->
<script>
	$(function () {
		$('.navbar-toggler').click(function () {
			$('body').toggleClass('noscroll');
		})
	});
</script>
<!--/scroll-down-JS-->
<!-- for blog carousel slider -->
<script src="/static/assets/js/owl.carousel.js"></script>
<!-- script for banner slider-->
<script>
	$(document).ready(function () {
		$('.owl-one').owlCarousel({
			loop: true,
			margin: 0,
			nav: false,
			responsiveClass: true,
			autoplay: false,
			autoplayTimeout: 5000,
			autoplaySpeed: 1000,
			autoplayHoverPause: false,
			responsive: {
				0: {
					items: 1,
					nav: false
				},
				480: {
					items: 1,
					nav: false
				},
				667: {
					items: 1,
					nav: true
				},
				1000: {
					items: 1,
					nav: true
				}
			}
		})
	})
</script>
<!-- //testimonials owlcarousel -->
<script>
	$(document).ready(function () {
		$('.owl-two').owlCarousel({
			loop: true,
			margin: 30,
			nav: false,
			responsiveClass: true,
			autoplay: false,
			autoplayTimeout: 5000,
			autoplaySpeed: 1000,
			autoplayHoverPause: false,
			responsive: {
				0: {
					items: 1,
					nav: false
				},
				480: {
					items: 1,
					nav: false
				},
				667: {
					items: 1,
					nav: false
				},
				1000: {
					items: 1,
					nav: false
				}
			}
		})
	})
</script>
<!-- //script for Testimonials-->
<!-- //script -->

<script src="/static/assets/js/bootstrap.min.js"></script>